### ISSUE TITLE
Examples and documentation

### ISSUE THREAD

**Issue by kemtrang** [Ghostbird/BUKrc20-telegram-bot#1]
hi i am newber. I want learn all command in libarry telegram bot. How can i search tutorial all command?

**Comment by Ghostbird** [comment]
[Here](https://github.com/python-telegram-bot/python-telegram-bot/wiki) you'll find the wiki for the telegram bot library used. It links to both examples and documentation. Have fun!

I'm closing this since it's not an issue with this repository.

**Comment by kemtrang** [comment]
thank you
